# Generated by Django 3.2.8 on 2021-10-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='super_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('company', models.TextField(null=True)),
                ('address', models.TextField()),
                ('website', models.TextField(null=True)),
                ('phone', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
