# Generated by Django 3.2.8 on 2021-10-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='super_admin',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
