# Generated by Django 3.2.8 on 2021-10-25 08:09

import SuperAdmin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0002_alter_super_admin_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='super_admin',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=SuperAdmin.models.filepath),
        ),
    ]
