# Generated by Django 3.2.7 on 2021-09-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210922_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='user_app_auth_conect',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
