# Generated by Django 3.2.7 on 2021-09-23 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_profile_user_app_auth_conect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='country',
        ),
    ]
