# Generated by Django 3.2.7 on 2021-09-23 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_profile_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='country',
        ),
    ]
