# Generated by Django 3.2.7 on 2021-09-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_delete_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='user',
            new_name='profile_user',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='image',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='/image/helen.jpg', null=True, upload_to=''),
        ),
    ]
