# Generated by Django 3.2.7 on 2021-09-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210923_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile_image',
            field=models.ImageField(default='/image/helen.jpg', upload_to=''),
        ),
    ]
