# Generated by Django 3.2.7 on 2021-09-23 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0009_alter_user_profile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='info_social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_code_user', models.TextField(blank=True, null=True)),
                ('ma_token_user', models.TextField(blank=True, null=True)),
                ('id_user_social', models.CharField(blank=True, max_length=255, null=True)),
                ('token_page_list', models.JSONField()),
                ('profile_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
