# Generated by Django 3.2.7 on 2021-09-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_info_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_social',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='info_social',
            name='name_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
