# Generated by Django 3.2.8 on 2021-10-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_delete_info_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_share_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_user', models.TextField()),
                ('page_link', models.TextField()),
                ('link_share', models.TextField()),
                ('count_view_site', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='share_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('code', models.TextField(unique=True)),
                ('code_invite', models.TextField(unique=True)),
                ('by_invite', models.TextField(default='No invite')),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='share_link_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('code', models.TextField()),
                ('page_link', models.TextField()),
                ('count_view_site', models.IntegerField()),
            ],
        ),
    ]
