# Generated by Django 3.2.8 on 2021-10-06 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_share_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_share_link',
        ),
    ]
