# Generated by Django 3.2.8 on 2021-10-09 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_share_link_share_link_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='share_link',
        ),
        migrations.DeleteModel(
            name='share_link_page',
        ),
    ]
