# Generated by Django 3.2.8 on 2021-10-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_create_share_link_link_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_share_link',
            name='time_share',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
