# Generated by Django 3.2.8 on 2021-10-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_create_share_link_time_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_share_link',
            name='time_share',
            field=models.IntegerField(default=10),
        ),
    ]
