# Generated by Django 3.2.8 on 2021-10-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_share_link_code_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share_link',
            name='address',
            field=models.TextField(default='No'),
        ),
    ]
