# Generated by Django 3.2.8 on 2021-10-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_share_link_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='share_link',
            name='by_invite',
            field=models.TextField(default='No invite'),
        ),
        migrations.AlterField(
            model_name='share_link',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='share_link',
            name='code_invite',
            field=models.TextField(unique=True),
        ),
    ]
