# Generated by Django 3.2.8 on 2021-10-06 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_rename_share_user_share_link_share_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share_link',
            old_name='share_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='share_link',
            old_name='share_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='share_link',
            old_name='share_user_id',
            new_name='user_id',
        ),
    ]
