# Generated by Django 3.2.8 on 2021-10-06 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20211006_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share_link',
            old_name='user_id',
            new_name='user',
        ),
    ]
