# Generated by Django 3.2.8 on 2021-10-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_rename_user_id_share_link_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share_link',
            name='user',
        ),
        migrations.AddField(
            model_name='share_link',
            name='user_id',
            field=models.TextField(default=2255225),
            preserve_default=False,
        ),
    ]
