# Generated by Django 3.2.8 on 2021-10-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20211006_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='share_link',
            name='count_view_site',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
