# Generated by Django 3.2.8 on 2021-10-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_share_link_count_view_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='share_link_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('page_link', models.TextField()),
                ('count_view_site', models.IntegerField(default=0)),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='share_link',
            name='code',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='share_link',
            name='count_view_site',
            field=models.IntegerField(default=0),
        ),
    ]
