# Generated by Django 3.2.8 on 2021-10-23 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_create_share_link_time_share'),
        ('user', '0018_auto_20211009_1702'),
        ('user', '0023_auto_20211007_1746'),
    ]

    operations = [
    ]
